### ISSUE TITLE
Hook not working in 6.2.2 CE GA3

### ISSUE THREAD

**Issue by alexweirig** [emiloberg/Liferay-Repeatable-Fields-Reorder-Hook#1]
Hello,

I noticed that the hook doesn't seem to work in 6.2.2 CE GA3.

The problem is located in the initSort() function in the JS part:

```
function initSort() {
    YUI().use('node', 'transition', function (Y) {
        // Capture clicks on up/down button
        // use a variable and check if it's not null 
        // otherwise web content creation fails in Liferay 6.2.2 CE GA3
        var ddmContainer = Y.one('.lfr-ddm-container');
        if (ddmContainer) {
            ddmContainer.delegate('click', moveDown, '.lfr-ddm-reorder-down-button');
            ddmContainer.delegate('click', moveUp, '.lfr-ddm-reorder-up-button');

            // Capture clicks on anything where we need to redraw the arrows.
            ddmContainer.delegate('click', updateArrowsAndButtons, '.lfr-ddm-repeatable-add-button');
            ddmContainer.delegate('click', updateArrowsAndButtons, '.lfr-ddm-repeatable-delete-button');
            updateArrowsAndButtons();
        }
    });
}
```

**Comment by emiloberg** [comment]
I haven't tested this in CE versions (well to be honest, it's not tested at all), it's just used in a 6.2 EE environment. 

But ouch, that was really bad code (by me)! Do you know why/when `Y.one('.lfr-ddm-container')` isn't found?

**Comment by emiloberg** [comment]
Feel free to send a pull request if you want to, or if you want to I can merge the lines manually.

**Comment by alexweirig** [comment]
Hi Emil,

I found that the Y.one(...) is null when I create a new web content from the Web Content Display portlet, i.e. place a new WCD portlet on a page and click the "Add" action.

The same problem seemed to occur when I created a new "basic" web content in the "control panel".

Alex

**Comment by alexweirig** [comment]
Sure, you can simply merge the lines of code.

**Comment by alexweirig** [comment]
BTW: Thanks a lot for the hook, it's really useful ... one wonders how the guys at Liferay can have missed this feature.

**Comment by emiloberg** [comment]
Pushed! Thanks for the heads up and fix!

And yeah, it really should be a build in function. I actually spoke with @jbalsas (and someone else who I can't remember who it was), who's a Liferay engineer for editor, about this at Liferay Devcon a couple of months ago. As I understood it, they just never really thought of it. Guess they haven't seen us using repeatable fields this way.

But see Chema! We do need this function, please add it to core ;)

One thing which needs to be fixed is that this does not currently work with wysiwygs as they need to be reinitialized when detached/reattached from/to the DOM. See issue #2.
